services:
  - type: web
    name: app
    env: python
    pythonVersion: 3.10  # Set your desired Python version
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  # Adjust based on your app's entry point
